/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuddiesRouteImport } from './routes/buddies'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as LetterLetterRouteImport } from './routes/letter.$letter'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddiesRoute = BuddiesRouteImport.update({
  id: '/buddies',
  path: '/buddies',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterLetterRoute = LetterLetterRouteImport.update({
  id: '/letter/$letter',
  path: '/letter/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buddies': typeof BuddiesRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/letter/$letter': typeof LetterLetterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buddies': typeof BuddiesRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/letter/$letter': typeof LetterLetterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buddies': typeof BuddiesRoute
  '/downloads': typeof DownloadsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/tts': typeof ApiTtsRoute
  '/letter/$letter': typeof LetterLetterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buddies'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/api/tts'
    | '/letter/$letter'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buddies'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/api/tts'
    | '/letter/$letter'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/buddies'
    | '/downloads'
    | '/login'
    | '/settings'
    | '/api/tts'
    | '/letter/$letter'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuddiesRoute: typeof BuddiesRoute
  DownloadsRoute: typeof DownloadsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiTtsRoute: typeof ApiTtsRoute
  LetterLetterRoute: typeof LetterLetterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddies': {
      id: '/buddies'
      path: '/buddies'
      fullPath: '/buddies'
      preLoaderRoute: typeof BuddiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter/$letter': {
      id: '/letter/$letter'
      path: '/letter/$letter'
      fullPath: '/letter/$letter'
      preLoaderRoute: typeof LetterLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuddiesRoute: BuddiesRoute,
  DownloadsRoute: DownloadsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiTtsRoute: ApiTtsRoute,
  LetterLetterRoute: LetterLetterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
